# Sử dụng version 3.3 cho nó mới
version: '3.3'

services:
  nginx:
    build: .
    image: demo-ngix-spa-404-fix
    container_name: demo-ngix-spa-404-fix
    ports:
      - "803:80"
    volumes:
      - ../code-fe/dist:/var/www/html
